
/* The model of a coniferous forest can be generated by building a very simplified tree model. 
The tree contains a cylinder and cone (with parametric height, radius and angular discretization).
 The tree model must be instantiated several times using as a translation vector on the scene the 
 three numbers generated by the coordinated functions of the digital terrain model.

Select one or more subsets of the ground to place the wooded areas on the slopes of the mountainous scene, 
adding a random term to increase the naturalness of the placement.*/









